### PR TITLE
Adds Card Design, Fixes Database Bug

### PR DESCRIPTION
**Pull request by paynemiller92**
# Summary of Changes
1. Adds Card View to Main Activity's Recycler View
2. Fixes bug where the most recent addition was not being loaded into Main Activity's Recycler View.

Addresses issue #29

### CODE REVIEW

**Comment by paynemiller92** [comment]
Here is a screenshot of the functionality. 

cardview

**Comment by Pritom14** [comment]
> **Add Information,click the "+" icon** 
 is for only when the `listView` is empty. Try to put that `textView` in the center when the `listView` is empty. Use `android:layout_centerInParent="true"` for it to be in the center

**Comment by Pritom14** [comment]
Also, in the `app/build.gradlle` file you should insert these lines  for travis check : 

> android {
>       lintOptions {
>           abortOnError false
>       }
>   }

And don't add all the files, like `.idea/gradle.xml` , `.idea/misc.xml` , `.idea/modules.xml`  are not required in the PR. Use `git status` and then add only the files which you have changed manually.
`git add <address of the file whcih you have changed` and not `git add --all`

**Comment by Pritom14** [comment]
For more help, do as they check in the `travis`. I mean click on the `Details` right beside `The Travs CI build failed`. It will redirect you to the `Travis` site and type the same commands as in the `travis` site, like :

> jdk_switcher use oraclejdk8
> git clone --depth=50 https://github.com/Pritom14/Password-Storage.git Pritom14/Password-Storage
> export TERM=dumb

and so on.
In the end you will get an output in your command line saying `Build Failed` or `Build Passed`. If it doesnot pass check for the error, solve the error and then send the PR. If you have any doubts I will be more than happy to help.

**Comment by paynemiller92** [comment]
@Pritom14 I will check on the Travis build, however, I did not see the specific idea/*.xml files within the README, so I assumed they were to be committed. If that is not the case, please either update the README or raise an issue so one of us may do so.

**Comment by Pritom14** [comment]
Okay, I will see to it that the README file is updated

**Comment by paynemiller92** [comment]
@Pritom14 The errors produced by Travis is the result of the build failing due to Lint errors. There are numerous Lint errors in the existing codebase, and it would be a sizable effort to clean all of them up. I will add the ignore lint errors command to grade **for now,** but I strongly recommend that we clean up all these errors in the future, as errors indicate unstable code.

**Comment by Pritom14** [comment]
Ohh!! That's bad. Can you add a new issue regarding the lint errors. I will
assign it to you

**Comment by paynemiller92** [comment]
@Pritom14 I have pushed the commit to ignore Lint errors, check it out once Travis is done and merge it in, then I will start cleaning up the Lint errors!

**Comment by paynemiller92** [comment]
@Pritom14 and I misspoke earlier, it's not the README that didn't contain the idea files, it was the .gitignore file, sorry about that!

**Review by Pritom14 — APPROVED** [review]

**Comment by Pritom14** [comment]
Could you please review #31

**Comment by paynemiller92** [comment]
@Pritom14 I have completed the review.

**Comment by Pritom14** [comment]
Thanks

**Comment by Pritom14** [comment]
**Add Information,click the "+" icon** is only for when the `listView` is empty. Could you change just that

**Comment by Pritom14** [comment]
@paynemiller92 ,you have to set the empty `textView` in the layout of `mainactivity` when there are no items on the list

**Comment by Pritom14** [comment]
Also the delete option for an item on the `listView` doesn't seem to work

**Comment by paynemiller92** [comment]
@Pritom14 I will knock those changes out today.

**Comment by Pritom14** [comment]
You might find these links helpful for using a `context menu` for  `recycleView` : [link 1](https://stackoverflow.com/questions/26466877/how-to-create-context-menu-for-recyclerview), [link 2](https://stackoverflow.com/questions/38607372/android-long-click-on-recyclerview-item-and-contextmenu),[link 3](https://stackoverflow.com/questions/30078344/handle-on-item-long-click-on-recycler-view),[link 4](https://gist.github.com/resengupta/2b2e26c949b28f8973e5), [link 5](https://gist.github.com/gauravat16/e8e03496a4056829e65dede3c236da28)

**Pull request closed without merging**
