### PR TITLE
Fixed issues with Travis integration

### PR DESCRIPTION
**Pull request by FrederikBolding**
As mentioned in #23

### CODE REVIEW

**Comment by Pritom14** [comment]
Why does it show, `build failed` when I open my account in travis

**Comment by Pritom14** [comment]
@FrederikBolding ,could you please check what went wrong?

**Comment by FrederikBolding** [comment]
@Pritom14 I'm not sure what went wrong with the pull request check. It doesn't seem related to my changes. But the most recent build worked fine: https://travis-ci.org/Pritom14/Password-Storage/builds/288543484

EDIT: As far as I can see from this: https://github.com/travis-ci/travis-ci/issues/5850 - It seems that the PR build failed because you had already merged the changes. Which is also why the master branch build worked fine.

**Comment by Pritom14** [comment]
Thanks. You could check out other issues in the repository.

**Pull request merged**
