### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by stupidly-logical**
Updated
Compile SDK Version
Build Tools Version
Target SDK Version
Android UI APIs
Firebase 
Butterknife

### CODE REVIEW

**Comment by Pritom14** [comment]
Could you please create an issue for this, and also refer that issue in your PR

**Comment by stupidly-logical** [comment]
Sure

**Comment by stupidly-logical** [comment]
Check #95

**Comment by Pritom14** [comment]
Change the version of `fabric` to `1.25.4` in `build.gradle(Project:Password-Storage)`, like this :
`classpath 'io.fabric.tools:gradle:1.25.4'`

**Comment by stupidly-logical** [comment]
A higher version 1.26.1 is available. Do you want me to use that or stick to 1.25.4?

**Comment by Pritom14** [comment]
You can use a higher version too

On 04-Oct-2018 11:11 PM, "Yash Krishan Verma" <notifications@github.com>
wrote:

A higher version 1.26.1 is available. Do you want me to use that or stick
to 1.25.4?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Pritom14/Password-Storage/pull/92#issuecomment-427107491>,
or mute the thread

**Comment by stupidly-logical** [comment]
@Pritom14 Done.

**Pull request merged**
