### PR TITLE
Toggle password in registration layout

### PR DESCRIPTION
**Pull request by stupidly-logical**
Changes for requirements in #93

### CODE REVIEW

**Comment by Pritom14** [comment]
If there are changes in the UI could you please add the screenshot in the screenshot folder

**Comment by stupidly-logical** [comment]
Screenshot added.

**Comment by stupidly-logical** [comment]
Kindly merge if tested and satisfied.

**Comment by stupidly-logical** [comment]
> If there are changes in the UI could you please add the screenshot in the screenshot folder

Done.

**Pull request merged**
