### PR TITLE
Main activity recycler view

### PR DESCRIPTION
**Pull request by paynemiller92**
# Summary of Changes

1. Converts ListView to RecyclerView on Main Activity
2. Creates an Adapter class for use inside of Recycler
3. Creates a layout file for use within the Adapter's View Holder

I tested the application and it works great!

### CODE REVIEW

**Comment by Pritom14** [comment]
Could you also please upload the screenshot of the screen

**Comment by paynemiller92** [comment]
This Pull Request references https://github.com/Pritom14/Password-Storage/issues/9

**Comment by paynemiller92** [comment]
@Pritom14 here are the screenshots you requested: 
password_detail
password_list

**Comment by Pritom14** [comment]
Kindly check your PR because some checks of travis are failing. Check the
travis command line instructions so you can get an idea of what mistakes
you have done in the changes

**Comment by paynemiller92** [comment]
The error seems to be ```W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease Unable to connect to ppa.launchpad.net:http:``` seems to be something with the Ubuntu distribution that Travis runs on?

**Review by Pritom14 — APPROVED** [review]
I guess as because the `os type is given as linux` in the `travis` file this error is caused

**Comment by Pritom14** [comment]
I will see to it that the `os type can be changed to windows` or not, meanwhile can you try to customize the `listview`. I want to implement `cardview` for each row in the `listview`. You can use the links given : [link 1](http://codesfor.in/android-listview-using-cardview-example/) , [link 2](https://stackoverflow.com/questions/30751870/can-one-use-cardview-for-listview-item-and-how) , [link 3](https://github.com/AndroidAppNotes/ListView-and-CardView)
Your desired output would be like the image given below : 
sample

**Comment by paynemiller92** [comment]
@Pritom14 Sure thing, however, can you please merge this branch, close issue #9 and reopen a new issue for the card view, containing the specs you require?

**Comment by Pritom14** [comment]
Sure

**Comment by Pritom14** [comment]
@paynemiller92 , also next time when you send a PR, see to it that the `app/build.gradle` contains these lines : 
```
android {
    lintOptions {
        abortOnError false
    }
}

```
It will take care of the `travis` check

**Comment by paynemiller92** [comment]
@Pritom14 will do.

**Pull request merged**
