### PR TITLE
Add Email pattern verification

### PR DESCRIPTION
**Pull request by stupidly-logical**
Added email pattern verification during sign up and login. #19

### CODE REVIEW

**Comment by Pritom14** [comment]
Thanks for the PR, but it has failed certain checks. Could you please check the `failed checks` and send a PR again. You can refer to this [link](https://github.com/travis-ci/travis-ci/issues/7110)

**Comment by stupidly-logical** [comment]
Okay

**Comment by stupidly-logical** [comment]
Unable to get past CI issue even after accepting all SDK licenses. This was the issue as reported by Travis log.

**Comment by Pritom14** [comment]
Ok, check the travis.yml file once. I think the problem lies in the file. I
don't have much idea on travis integration.

**Comment by stupidly-logical** [comment]
I am building with sdk 25 whereas in the yml only 22 is mentioned. I'll change and then make the RP.

**Comment by Pritom14** [comment]
Try to change in a way so that no more checks are failed if someone makes a
PR ,due to travis integration.

**Review by Pritom14 — COMMENTED** [review]
Check it in your system as the in the way travis integration builds in the command line. If all goes well inform me , I will approve it.

**Comment by Pritom14** [comment]
Click on the `details` option next to `some checks have failed` . You will get the steps/commands as to how travis builds.

**Review by Pritom14 — COMMENTED** [review]
Please try to omit the XML files except strings.xml

**Comment by Pritom14** [comment]
and try to send the PR on the master branch

**Comment by stupidly-logical** [comment]
Okay, will do this in few hours.

**Comment by Pritom14** [comment]
I am closing this PR, hope you can send another PR where you clear out your mistakes.
Thanks

**Pull request closed without merging**
