### PR TITLE
Issue - Setup Continuous integration with Travis CI #11

### PR DESCRIPTION
**Pull request by diegorramos**
Created file .travis.yml for the integration TravisCI. Maybe you need configure some things.

- You need create account TravisCI
- You need configure version android on file .travis.yml.

### CODE REVIEW

**Comment by Pritom14** [comment]
Thanks for the PR.
Can you please describe all the steps because I already have an account TravisCI. And where do I need to configure android on file .travis.yml

**Comment by Polovinsky** [comment]
I realized that you already have the file .travis.yml. It is already running?

**Comment by Pritom14** [comment]
Please resolve the conflicts.

**Comment by Pritom14** [comment]
@Polovinsky , please try to modify the travis.yml file so that android-sdk 25 passes through the checks, because some PRs although correct are not able to pass the checks

**Comment by diegorramos** [comment]
Sure!

**Comment by diegorramos** [comment]
Did you get the PR I sent?

**Comment by Pritom14** [comment]
Yes, I got but the issue for Travis integration has been solved already.
Could you please check out some other issue

**Pull request merged**
