### PR TITLE
Travis CI integration 

### PR DESCRIPTION
**Pull request by geoemm**
The changes in gradle.properties are required because they are breaking the travis build.

### CODE REVIEW

**Comment by geoemm** [comment]
After a bit of googling I think the values on gradle.properties are machine/network related. (Yours specifically). Are they required?

**Comment by Pritom14** [comment]
Don't change the gradle properties. Just submit a PR with the licenses and
travis.yml

**Comment by geoemm** [comment]
Ok I reverted the changes and only travis and android-licenses folder are left.

**Comment by Pritom14** [comment]
Thanks for the PR

**Comment by Pritom14** [comment]
Please try to implement the travis integration again because the build was continuously failing due to some issues, so I has to delete all the licenses as well as the `.travis.yml` file

**Comment by geoemm** [comment]
It fails and the reason is the grade.properties file. Comment the content and again.

**Comment by Pritom14** [comment]
Could you please fix this?

**Comment by Pritom14** [comment]
and please keep the Android SDK version to be 25

**Pull request merged**
