### PR TITLE
revamp detail design

### LINKED ISSUE #34: Revamp the DetailsActivity
Make sure to follow the material design guidelines

### PR DESCRIPTION
**Pull request by anandwana001**
Fix #34 Revamp the DetailsActivity

### CODE REVIEW

**Comment by Pritom14** [comment]
@anandwana001 , push your commits directly into the master branch and also remove the .idea file

**Comment by Pritom14** [comment]
I am unable to merge your PR due to some issues, I haven't tried the command line instructions. I would suggest you to send the PR again, making the same modifications on the master branch

**Comment by anandwana001** [comment]
@Pritom14` >>>>master =====` these kinds of lines get added inside the code, I removed these lines but don't understand that how these lines are getting added!! if you could help

**Comment by Pritom14** [comment]
I am not able to figure it out since that day, I suggest you close the PR and send a new one.

**Comment by anandwana001** [comment]
ok

**Pull request closed without merging**
