### PR TITLE
Minor UI Enhancements.

### PR DESCRIPTION
**Pull request by rizal-rovins**
Changed the primary colors.
Added padding to dialogs for a cleaner look.
Changed background to a gradient.

### CODE REVIEW

**Comment by Pritom14** [comment]
Thank you for the PR, could you please upload the screenshots

**Review by Pritom14 — CHANGES_REQUESTED** [review]
The idea files cannot be merged. Please change these

**Review by rizal-rovins — COMMENTED** [review]
Idea files changed.

**Comment by rizal-rovins** [comment]
screenshot_20171008-141604
screenshot_20171008-141613
screenshot_20171008-141620




screenshot_20171008-141543

**Comment by Pritom14** [comment]
Thanks a lot for the PR, I will merge it after the other reviewers review it

**Comment by Pritom14** [comment]
Close this PR and make a new PR, because the checks in travis integration have failed.

**Pull request closed without merging**
